// ─── CATALOGUE DES THÈMES JOUEUR + BOUTIQUE ───────────────────
// Extrait de App.jsx (Lot 5 #24, découpage progressif) : module purement de données,
// aucune fonction ne fait d'appel externe ici (vérifié avant extraction) — zéro état
// partagé, zéro changement de comportement.

// ─── PLAYER THEME CATALOG ────────────────────────────────────
export const PLAYER_THEMES = {
  none: {
    id:"none", name:"Aucun", icon:"⬜",
    bg:"#1a1a2e", primary:"#5D9E34", accent:"#D9BC5C", glow:"#D9BC5C",
    levels:["Débutant","Aventurier","Héros","Champion","LÉGENDE"],
    levelsF:["Débutante","Aventurière","Héroïne","Championne","LÉGENDE"],
    taskVerb:"complétée", winMsg:"Mission accomplie!", coinName:"Pièce",
    platformBg:"#1a1a2e", platformColor:"#5D9E34", platformItem:"⭐",
    platformItems:["⭐","💫","✨","🌟","💎"],
    platformHazard:null, platformObstacle:"🪨",
    charBodyColor:null, // null = use player.color
    shopCategory:{ id:"themed", label:"🎯 Items", items:[] },
  },
  lego: {
    id:"lego", name:"LEGO", icon:"🧱",
    bg:"#1a1a0a", primary:"#E3000B", accent:"#D9BC5C", glow:"#D9BC5C",
    levels:["Apprenti","Constructeur","Architecte","Maître","LEGO MASTER"],
    levelsF:["Apprentie","Constructrice","Architecte","Maître","LEGO MASTER"],
    taskVerb:"construite", winMsg:"Tu as construit cette quête!", coinName:"Brique",
    platformBg:"#2a2a00", platformColor:"#E3000B", platformItem:"🧱",
    platformItems:["🧱","⚙️","🪄","🔵","🟡"],
    platformHazard:"💥", platformObstacle:"🟥",
    charBodyColor:"#D9BC5C",
    shopCategory:{ id:"lego", label:"🧱 LEGO", items:[
      {id:"lg1",emoji:"🧱",name:"Brique légendaire",  cost:20,slot:"themed"},
      {id:"lg2",emoji:"🪄",name:"Minifig spéciale",   cost:35,slot:"themed"},
      {id:"lg3",emoji:"🏗️",name:"Set exclusif",       cost:50,slot:"themed"},
      {id:"lg4",emoji:"⚙️",name:"Pièce technique",    cost:15,slot:"themed"},
      {id:"lg5",emoji:"🎭",name:"Tête d'expression",  cost:25,slot:"face"},
      {id:"lg6",emoji:"🟡",name:"Tête jaune classique",cost:12,slot:"face"},
    ]},
  },
  medieval: {
    id:"medieval", name:"Médiéval", icon:"⚔️",
    bg:"#1a1400", primary:"#8B6914", accent:"#DAA520", glow:"#D9BC5C",
    levels:["Paysan","Écuyer","Chevalier","Seigneur","ROI"],
    levelsF:["Paysanne","Écuyère","Chevalière","Dame","REINE"],
    taskVerb:"accomplie", winMsg:"Quête accomplie, noble guerrier!", coinName:"Pièce d'or",
    platformBg:"#0a0800", platformColor:"#8B6914", platformItem:"📜",
    platformItems:["📜","🗡️","🛡️","👑","💎"],
    platformHazard:"🔥", platformObstacle:"🪨",
    charBodyColor:"#8B6914",
    shopCategory:{ id:"medieval", label:"⚔️ Médiéval", items:[
      {id:"md1",emoji:"🗡️",name:"Épée légendaire",    cost:35,slot:"themed"},
      {id:"md2",emoji:"🛡️",name:"Bouclier héraldique",cost:25,slot:"themed"},
      {id:"md3",emoji:"👑",name:"Couronne royale",     cost:50,slot:"hat"},
      {id:"md4",emoji:"🏰",name:"Château miniature",   cost:60,slot:"themed"},
      {id:"md5",emoji:"📜",name:"Parchemin rare",      cost:15,slot:"themed"},
      {id:"md6",emoji:"🪖",name:"Heaume de chevalier", cost:30,slot:"hat"},
    ]},
  },
  kpop: {
    id:"kpop", name:"K-Pop", icon:"🎤",
    bg:"#0a0010", primary:"#CC00AA", accent:"#FF69B4", glow:"#FF69B4",
    levels:["Trainee","Idol","Center","Soliste","SUPERSTAR"],
    levelsF:["Trainee","Idol","Center","Soliste","SUPERSTAR"],
    taskVerb:"performée", winMsg:"Le fandom t'adore!", coinName:"Lightstick",
    platformBg:"#050005", platformColor:"#CC00AA", platformItem:"🎵",
    platformItems:["🎵","🎤","💿","🌟","💜"],
    platformHazard:"📸", platformObstacle:"🎸",
    charBodyColor:"#CC00AA",
    shopCategory:{ id:"kpop", label:"🎤 K-Pop", items:[
      {id:"kp1",emoji:"🎤",name:"Micro légendaire",  cost:35,slot:"themed"},
      {id:"kp2",emoji:"💿",name:"Album signé",       cost:40,slot:"themed"},
      {id:"kp3",emoji:"🌟",name:"Lightstick ultime", cost:25,slot:"themed"},
      {id:"kp4",emoji:"👟",name:"Souliers de scène", cost:20,slot:"themed"},
      {id:"kp5",emoji:"🎧",name:"Casque studio",     cost:30,slot:"hat"},
      {id:"kp6",emoji:"💜",name:"Ruban ARMY",        cost:15,slot:"themed"},
    ]},
  },
  unicorn: {
    id:"unicorn", name:"Licornes", icon:"🦄",
    bg:"#0a0015", primary:"#DD44FF", accent:"#FFB3FF", glow:"#FFB3FF",
    levels:["Poulain","Licorne","Licorne Ailée","Licorne Arc-en-ciel","LICORNE LÉGENDAIRE"],
    levelsF:["Pouliche","Licorne","Licorne Ailée","Licorne Arc-en-ciel","LICORNE LÉGENDAIRE"],
    taskVerb:"enchantée", winMsg:"Ta corne brille! Le royaume t'acclame!", coinName:"Poussière de fée",
    platformBg:"#050008", platformColor:"#DD44FF", platformItem:"🌈",
    platformItems:["🌈","✨","🌸","💎","🧁"],
    platformHazard:"🌩️", platformObstacle:"☁️",
    charBodyColor:"#DD44FF",
    shopCategory:{ id:"unicorn", label:"🦄 Licorne", items:[
      {id:"un1",emoji:"🌈",name:"Arc-en-ciel en bouteille",cost:30,slot:"themed"},
      {id:"un2",emoji:"✨",name:"Poussière de fée",         cost:15,slot:"themed"},
      {id:"un3",emoji:"🌸",name:"Fleur magique",            cost:20,slot:"themed"},
      {id:"un4",emoji:"💎",name:"Cristal de corne",         cost:50,slot:"themed"},
      {id:"un5",emoji:"🧁",name:"Cupcake enchanté",         cost:25,slot:"themed"},
      {id:"un6",emoji:"🎀",name:"Ruban arc-en-ciel",        cost:12,slot:"hat"},
    ]},
  },
  demon: {
    id:"demon", name:"Démons", icon:"😈",
    bg:"#0a0000", primary:"#CC1100", accent:"#FF3300", glow:"#FF0066",
    levels:["Imp","Diablotin","Démon","Archidémon","SEIGNEUR DES OMBRES"],
    levelsF:["Imp","Diablotine","Démone","Archidémone","SEIGNEURE DES OMBRES"],
    taskVerb:"dominée", winMsg:"Le chaos s'incline! L'enfer t'acclame!", coinName:"Âme",
    platformBg:"#050000", platformColor:"#CC1100", platformItem:"🔥",
    platformItems:["🔥","💀","🧿","⛓️","🌋"],
    platformHazard:"💥", platformObstacle:"🪨",
    charBodyColor:"#1a0000",
    shopCategory:{ id:"demon", label:"😈 Démon", items:[
      {id:"dm1",emoji:"💀",name:"Crâne rare",            cost:30,slot:"themed"},
      {id:"dm2",emoji:"🔥",name:"Flamme éternelle",      cost:25,slot:"themed"},
      {id:"dm3",emoji:"🧿",name:"Œil démoniaque",        cost:35,slot:"themed"},
      {id:"dm4",emoji:"⛓️",name:"Chaîne légendaire",     cost:40,slot:"themed"},
      {id:"dm5",emoji:"🌋",name:"Fragment de volcan",     cost:20,slot:"themed"},
      {id:"dm6",emoji:"😈",name:"Cornes de boss",         cost:50,slot:"hat"},
    ]},
  },
  angel: {
    id:"angel", name:"Anges", icon:"😇",
    bg:"#00040a", primary:"#6699FF", accent:"#FFE566", glow:"#FFFFAA",
    levels:["Novice Céleste","Chérubin","Ange Gardien","Archange","SÉRAPHIN"],
    levelsF:["Novice Céleste","Chérubin","Ange Gardienne","Archange","SÉRAPHIN"],
    taskVerb:"bénie", winMsg:"Les cieux chantent! Les anges t'applaudissent!", coinName:"Étoile",
    platformBg:"#000508", platformColor:"#6699FF", platformItem:"⭐",
    platformItems:["⭐","🪶","🎺","💫","📿"],
    platformHazard:"⚡", platformObstacle:"☁️",
    charBodyColor:"#E8F4FF",
    shopCategory:{ id:"angel", label:"😇 Ange", items:[
      {id:"ag1",emoji:"🌟",name:"Étoile céleste",       cost:25,slot:"themed"},
      {id:"ag2",emoji:"🪶",name:"Plume sacrée",          cost:20,slot:"themed"},
      {id:"ag3",emoji:"🎺",name:"Trompette dorée",       cost:35,slot:"themed"},
      {id:"ag4",emoji:"💫",name:"Sphère lumineuse",      cost:30,slot:"themed"},
      {id:"ag5",emoji:"📿",name:"Chapelet enchanté",     cost:15,slot:"themed"},
      {id:"ag6",emoji:"😇",name:"Auréole divine",        cost:50,slot:"hat"},
    ]},
  },
  // ── SCIENTIFIQUE ──────────────────────────────────────────
  scientifique: {
    id:"scientifique", name:"Scientifique", icon:"🔬",
    bg:"#001a0a", primary:"#00CC66", accent:"#00FF99", glow:"#00FF99",
    levels:["Cobaye","Stagiaire","Chercheur","Professeur","PRIX NOBEL"],
    levelsF:["Cobaye","Stagiaire","Chercheuse","Professeure","PRIX NOBEL"],
    taskVerb:"prouvée", winMsg:"L'hypothèse est confirmée. Pour une fois.",
    coinName:"Molécule",
    platformBg:"#000d05", platformColor:"#00CC66", platformItem:"🧪",
    platformItems:["🧪","⚗️","🔭","💉","🧬"], platformHazard:"☢️", platformObstacle:"🧱",
    charBodyColor:"#004422",
    shopCategory:{ id:"scientifique", label:"🔬 Labo", items:[
      {id:"sc1",emoji:"🔬",name:"Microscope ultime",cost:35,slot:"themed"},
      {id:"sc2",emoji:"🥼",name:"Blouse trouée (rare)",cost:20,slot:"themed"},
      {id:"sc3",emoji:"🏆",name:"Trophée Nobel raté",cost:50,slot:"themed"},
      {id:"sc4",emoji:"⚗️",name:"Éprouvette légendaire",cost:25,slot:"themed"},
      {id:"sc5",emoji:"🧬",name:"ADN personnalisé",cost:40,slot:"themed"},
      {id:"sc6",emoji:"🎓",name:"Chapeau de docteur",cost:30,slot:"hat"},
    ]},
  },
  // ── INSECTES ──────────────────────────────────────────────
  insectes: {
    id:"insectes", name:"Insectes", icon:"🐛",
    bg:"#0a1400", primary:"#66AA00", accent:"#AAFF00", glow:"#AAFF00",
    levels:["Oeuf","Larve","Chrysalide","Insecte","REINE DES BUGS"],
    levelsF:["Oeuf","Larve","Chrysalide","Insecte","REINE DES BUGS"],
    taskVerb:"butinée", winMsg:"Même une fourmi travaille. Leçon de vie.",
    coinName:"Larve",
    platformBg:"#050a00", platformColor:"#66AA00", platformItem:"🌿",
    platformItems:["🌿","🌸","🍄","💧","🪲"], platformHazard:"🕷️", platformObstacle:"🪨",
    charBodyColor:"#335500",
    shopCategory:{ id:"insectes", label:"🐛 Insectes", items:[
      {id:"in1",emoji:"🦋",name:"Ailes de papillon",cost:30,slot:"themed"},
      {id:"in2",emoji:"🐞",name:"Carapace coccinelle",cost:25,slot:"themed"},
      {id:"in3",emoji:"🦗",name:"Antennes grillon",cost:20,slot:"hat"},
      {id:"in4",emoji:"🪲",name:"Cocon doré",cost:50,slot:"themed"},
      {id:"in5",emoji:"🐜",name:"Armure fourmi",cost:35,slot:"themed"},
      {id:"in6",emoji:"🌿",name:"Branche camouflage",cost:15,slot:"themed"},
    ]},
  },
  // ── MONSTRES ──────────────────────────────────────────────
  monstres: {
    id:"monstres", name:"Monstres", icon:"👹",
    bg:"#1a0020", primary:"#8800CC", accent:"#CC44FF", glow:"#CC44FF",
    levels:["Petit Monstre","Croqueur","Grognard","Terroriseur","MONSTRE SUPRÊME"],
    levelsF:["Petite Monstre","Croqueuse","Grognarde","Terroriseuse","MONSTRE SUPRÊME"],
    taskVerb:"dévorée", winMsg:"Frankenstein faisait ses tâches. Probablement.",
    coinName:"Rugissement",
    platformBg:"#0d0015", platformColor:"#8800CC", platformItem:"💜",
    platformItems:["💜","🦷","👁️","⛓️","💀"], platformHazard:"🔥", platformObstacle:"🪨",
    charBodyColor:"#440066",
    shopCategory:{ id:"monstres", label:"👹 Monstres", items:[
      {id:"mo1",emoji:"👹",name:"Masque de monstre",cost:35,slot:"hat"},
      {id:"mo2",emoji:"🦷",name:"Dents géantes",cost:25,slot:"themed"},
      {id:"mo3",emoji:"💜",name:"Cape de monstre",cost:30,slot:"themed"},
      {id:"mo4",emoji:"⛓️",name:"Chaînes de boss",cost:40,slot:"themed"},
      {id:"mo5",emoji:"👁️",name:"Œil central",cost:20,slot:"themed"},
      {id:"mo6",emoji:"🖤",name:"Coeur de ténèbres",cost:50,slot:"themed"},
    ]},
  },
  // ── PRÉHISTOIRE ───────────────────────────────────────────
  prehistoire: {
    id:"prehistoire", name:"Préhistoire", icon:"🦕",
    bg:"#1a1000", primary:"#AA6600", accent:"#FFAA00", glow:"#FFAA00",
    levels:["Homo Canapé","Chasseur","Troglodyte","Chef de Clan","DIEU DE LA CAVERNE"],
    levelsF:["Homo Canapé","Chasseuse","Troglodyte","Cheffe de Clan","DIEU DE LA CAVERNE"],
    taskVerb:"chassée", winMsg:"Les dinosaures ont arrêté de ranger. C'est pour ça qu'ils ont disparu.",
    coinName:"Os",
    platformBg:"#0d0800", platformColor:"#AA6600", platformItem:"🦴",
    platformItems:["🦴","🪨","🌋","🦕","🥚"], platformHazard:"🌋", platformObstacle:"🪨",
    charBodyColor:"#664400",
    shopCategory:{ id:"prehistoire", label:"🦕 Préhistoire", items:[
      {id:"pr1",emoji:"🪨",name:"Massue de roche",cost:20,slot:"themed"},
      {id:"pr2",emoji:"🦣",name:"Peau de mammouth",cost:35,slot:"themed"},
      {id:"pr3",emoji:"🖼️",name:"Peinture rupestre",cost:25,slot:"themed"},
      {id:"pr4",emoji:"🦕",name:"Œuf de dinosaure",cost:50,slot:"themed"},
      {id:"pr5",emoji:"🪶",name:"Parure de chef",cost:30,slot:"hat"},
      {id:"pr6",emoji:"🔥",name:"Feu sacré",cost:15,slot:"themed"},
    ]},
  },
  // ── MICROSCOPIQUE ─────────────────────────────────────────
  microscopique: {
    id:"microscopique", name:"Microscopique", icon:"🦠",
    bg:"#000a14", primary:"#0088CC", accent:"#00DDFF", glow:"#00DDFF",
    levels:["Virus","Microbe","Bactérie","Cellule","ORGANISME ENTIER"],
    levelsF:["Virus","Microbe","Bactérie","Cellule","ORGANISME ENTIER"],
    taskVerb:"divisée", winMsg:"Tu es officiellement plus organisé qu'une amibe. C'est un compliment.",
    coinName:"Bactérie",
    platformBg:"#00050a", platformColor:"#0088CC", platformItem:"💉",
    platformItems:["💉","🔵","⚪","🧬","🫧"], platformHazard:"⚡", platformObstacle:"🫧",
    charBodyColor:"#003344",
    shopCategory:{ id:"microscopique", label:"🦠 Micro", items:[
      {id:"mi1",emoji:"🦠",name:"Flagelle doré",cost:30,slot:"themed"},
      {id:"mi2",emoji:"🔵",name:"Noyau cellulaire",cost:25,slot:"themed"},
      {id:"mi3",emoji:"🧬",name:"Mitochondrie légendaire",cost:50,slot:"themed"},
      {id:"mi4",emoji:"💉",name:"Seringue de pouvoir",cost:20,slot:"themed"},
      {id:"mi5",emoji:"🫧",name:"Bulle protectrice",cost:35,slot:"themed"},
      {id:"mi6",emoji:"⚗️",name:"Pipette d'élite",cost:15,slot:"themed"},
    ]},
  },
  // ── ROBLOX ────────────────────────────────────────────────
  roblox: {
    id:"roblox", name:"Roblox", icon:"🎮",
    bg:"#0a0a0a", primary:"#CC0000", accent:"#D97070", glow:"#FF6666",
    levels:["Noob","Builder","Pro","Admin","OWNER"],
    levelsF:["Noob","Builder","Pro","Admin","OWNER"],
    taskVerb:"obbyée", winMsg:"OOF. Quête complétée. Tu n'es plus un noob. Presque.",
    coinName:"Robux fictif",
    platformBg:"#050505", platformColor:"#CC0000", platformItem:"🧱",
    platformItems:["🧱","⭐","💎","🎯","🏆"], platformHazard:"💥", platformObstacle:"🟥",
    charBodyColor:"#880000",
    shopCategory:{ id:"roblox", label:"🎮 Roblox", items:[
      {id:"rb1",emoji:"🧢",name:"Chapeau aux oeufs",cost:25,slot:"hat"},
      {id:"rb2",emoji:"💎",name:"Gemme Admin",cost:50,slot:"themed"},
      {id:"rb3",emoji:"🏠",name:"Brique ultime",cost:20,slot:"themed"},
      {id:"rb4",emoji:"⚔️",name:"Épée légendaire obby",cost:35,slot:"themed"},
      {id:"rb5",emoji:"🛡️",name:"Bouclier noob+",cost:15,slot:"themed"},
      {id:"rb6",emoji:"🏆",name:"Trophée Owner",cost:60,slot:"themed"},
    ]},
  },
  // ── BISOUNOURS ────────────────────────────────────────────
  bisounours: {
    id:"bisounours", name:"Rose Bisounours 🆘", icon:"🌈",
    bg:"#1a0010", primary:"#FF69B4", accent:"#FFB3FF", glow:"#FFB3FF",
    levels:["Bébé Bisounours","Super Doux","Trop Mignon","Câlinosaure","GRAND MAÎTRE DU ROSE"],
    levelsF:["Bébé Bisounours","Super Douce","Trop Mignonne","Câlinosaure","GRAND MAÎTRE DU ROSE"],
    taskVerb:"câlinée", winMsg:"Félicitations! Tu as gagné un arc-en-ciel supplémentaire. ENCORE UN.",
    coinName:"Câlin forcé",
    platformBg:"#0f000a", platformColor:"#FF69B4", platformItem:"🌈",
    platformItems:["🌈","💝","✨","🦄","☁️"], platformHazard:"💖", platformObstacle:"☁️",
    charBodyColor:"#CC0066",
    shopCategory:{ id:"bisounours", label:"🌈 Bisounours", items:[
      {id:"bs1",emoji:"☁️",name:"Nuage rose",cost:15,slot:"themed"},
      {id:"bs2",emoji:"💝",name:"Coeur géant",cost:20,slot:"themed"},
      {id:"bs3",emoji:"🌈",name:"Arc-en-ciel en plastique",cost:25,slot:"themed"},
      {id:"bs4",emoji:"✨",name:"Paillettes obligatoires",cost:30,slot:"themed"},
      {id:"bs5",emoji:"🦄",name:"Licorne bonus",cost:50,slot:"pet"},
      {id:"bs6",emoji:"🎀",name:"Noeud rose fluo",cost:10,slot:"hat"},
    ]},
  },
  // ── CUISINE ───────────────────────────────────────────────
  cuisine: {
    id:"cuisine", name:"Cuisine", icon:"🍳",
    bg:"#14080a", primary:"#CC4400", accent:"#FF8844", glow:"#FF8844",
    levels:["Lave-Vaisselle","Apprenti","Sous-Chef","Chef","GORDON RAMSAY"],
    levelsF:["Lave-Vaisselle","Apprentie","Sous-Cheffe","Cheffe","GORDON RAMSAY"],
    taskVerb:"cuisinée", winMsg:"C'est pas encore brûlé. Progrès.",
    coinName:"Étoile Michelin",
    platformBg:"#0a0405", platformColor:"#CC4400", platformItem:"🍳",
    platformItems:["🍳","🥄","🔪","🧂","🏆"], platformHazard:"🔥", platformObstacle:"🫕",
    charBodyColor:"#881100",
    shopCategory:{ id:"cuisine", label:"🍳 Cuisine", items:[
      {id:"cu1",emoji:"👨‍🍳",name:"Toque de chef",cost:25,slot:"hat"},
      {id:"cu2",emoji:"👔",name:"Tablier légendaire",cost:20,slot:"themed"},
      {id:"cu3",emoji:"🔪",name:"Couteau pro",cost:35,slot:"themed"},
      {id:"cu4",emoji:"🥄",name:"Spatule d'or",cost:30,slot:"themed"},
      {id:"cu5",emoji:"⭐",name:"3 étoiles Michelin",cost:60,slot:"themed"},
      {id:"cu6",emoji:"🍕",name:"Pizza magique",cost:15,slot:"themed"},
    ]},
  },
  // ── HORREUR ───────────────────────────────────────────────
  horreur: {
    id:"horreur", name:"Horreur", icon:"😱",
    bg:"#050005", primary:"#880000", accent:"#FF2222", glow:"#D97070",
    levels:["Trouillard","Nerveux","Courageux","Survivant","DERNIER SURVIVANT"],
    levelsF:["Trouillarde","Nerveuse","Courageuse","Survivante","DERNIER SURVIVANT"],
    taskVerb:"survécue", winMsg:"Tu as accompli ça. Dans le noir. Sans mourir. Impressive.",
    coinName:"Frisson",
    platformBg:"#020002", platformColor:"#880000", platformItem:"🔦",
    platformItems:["🔦","🗝️","📿","🩸","💀"], platformHazard:"👻", platformObstacle:"⛓️",
    charBodyColor:"#330000",
    shopCategory:{ id:"horreur", label:"😱 Horreur", items:[
      {id:"ho1",emoji:"🔦",name:"Lampe de poche",cost:15,slot:"themed"},
      {id:"ho2",emoji:"🎭",name:"Masque de hockey",cost:30,slot:"hat"},
      {id:"ho3",emoji:"🗝️",name:"Clé de la cave",cost:25,slot:"themed"},
      {id:"ho4",emoji:"📿",name:"Amulette protectrice",cost:35,slot:"themed"},
      {id:"ho5",emoji:"🩸",name:"Stigmate du survivant",cost:50,slot:"themed"},
      {id:"ho6",emoji:"💀",name:"Crâne du boss final",cost:40,slot:"themed"},
    ]},
  },
  // ── TOTALEMENT MÉLANGÉ ────────────────────────────────────
  melange: {
    id:"melange", name:"Totalement Mélangé", icon:"🌪️",
    bg:"#0a0a14", primary:"#8844CC", accent:"#FFCC00", glow:"#FFCC00",
    levels:["Chaos","Confusion","Désordre Organisé","Anarchie","C'EST QUI LE BOSS ICI?"],
    levelsF:["Chaos","Confusion","Désordre Organisé","Anarchie","C'EST QUI LE BOSS ICI?"],
    taskVerb:"chaotisée", winMsg:"Un dinosaure Bisounours scientifique vient de valider ça. Normal.",
    coinName:"Truc",
    platformBg:"#050510", platformColor:"#8844CC", platformItem:"🌀",
    platformItems:["🌀","🦕","🌈","🔬","🎮"], platformHazard:"❓", platformObstacle:"🌪️",
    charBodyColor:null, // random each render
    mixedMode:true, // signals UI to slowly cycle accent color
    shopCategory:{ id:"melange", label:"🌪️ Chaos", items:[
      {id:"mx1",emoji:"🌪️",name:"Tourbillon de trucs",cost:20,slot:"themed"},
      {id:"mx2",emoji:"❓",name:"Item mystère",cost:25,slot:"themed"},
      {id:"mx3",emoji:"🦕",name:"Dino-Bisounours",cost:35,slot:"pet"},
      {id:"mx4",emoji:"🌈",name:"Arc-en-ciel scientifique",cost:30,slot:"themed"},
      {id:"mx5",emoji:"🎲",name:"Dé du destin",cost:15,slot:"themed"},
      {id:"mx6",emoji:"🌀",name:"Chapeau de chaos",cost:40,slot:"hat"},
    ]},
  },
  // ── HARRY POTTER ──────────────────────────────────────────
  harrypotter: {
    id:"harrypotter", name:"Harry Potter", icon:"🪄",
    bg:"#07060d", primary:"#7B2FBE", accent:"#F0C040", glow:"#F0C040",
    levels:["Moldu","Élève","Préfet","Auror","SORCIER SUPRÊME"],
    levelsF:["Moldue","Élève","Préfète","Auror","SORCIÈRE SUPRÊME"],
    taskVerb:"ensorcelée", winMsg:"Hermione aurait déjà fini. Juste dit.",
    coinName:"Gallion",
    platformBg:"#040309", platformColor:"#7B2FBE", platformItem:"✨",
    platformItems:["✨","🪄","📚","🦉","⚡"], platformHazard:"🧙",  platformObstacle:"🪨",
    charBodyColor:"#3d1a6e",
    shopCategory:{ id:"harrypotter", label:"🪄 Poudlard", items:[
      {id:"hp1",emoji:"🪄",name:"Baguette en bois de houx",cost:30,slot:"themed"},
      {id:"hp2",emoji:"🧣",name:"Écharpe de maison",cost:20,slot:"themed"},
      {id:"hp3",emoji:"🎓",name:"Chapeau du Choixpeau",cost:40,slot:"hat"},
      {id:"hp4",emoji:"🦉",name:"Hibou messager",cost:35,slot:"pet"},
      {id:"hp5",emoji:"🏆",name:"Coupe des Quatre Maisons",cost:60,slot:"themed"},
      {id:"hp6",emoji:"🔮",name:"Boule de cristal",cost:25,slot:"themed"},
    ]},
  },
  // ── GÉANT DE FER ──────────────────────────────────────────
  geantdefer: {
    id:"geantdefer", name:"Géant de Fer", icon:"🤖",
    bg:"#050a10", primary:"#4477CC", accent:"#88CCFF", glow:"#88CCFF",
    levels:["Ferraille","Robot","Androïde","Géant","SUPERMAN (le vrai)"],
    levelsF:["Ferraille","Robot","Androïde","Géante","SUPERMAN (le vrai)"],
    taskVerb:"boulonnée", winMsg:"Tu n'es pas une arme. Tu es un héros. Maintenant range ta chambre.",
    coinName:"Boulon",
    platformBg:"#020508", platformColor:"#4477CC", platformItem:"⚙️",
    platformItems:["⚙️","🔩","🦾","💥","⭐"], platformHazard:"🚀", platformObstacle:"🪨",
    charBodyColor:"#2244AA",
    shopCategory:{ id:"geantdefer", label:"🤖 Géant", items:[
      {id:"gi1",emoji:"🦾",name:"Poing de métal",cost:30,slot:"themed"},
      {id:"gi2",emoji:"👁️",name:"Laser oculaire",cost:35,slot:"themed"},
      {id:"gi3",emoji:"🛡️",name:"Plaque de blindage",cost:40,slot:"themed"},
      {id:"gi4",emoji:"⭐",name:"Étoile de Superman",cost:50,slot:"themed"},
      {id:"gi5",emoji:"🔩",name:"Boulon légendaire",cost:20,slot:"themed"},
      {id:"gi6",emoji:"🪖",name:"Casque de titane",cost:25,slot:"hat"},
    ]},
  },
  // ── LES TROLLS ────────────────────────────────────────────
  trolls: {
    id:"trolls", name:"Les Trolls", icon:"🧌",
    bg:"#0a0014", primary:"#CC44AA", accent:"#FF88FF", glow:"#FF88FF",
    levels:["Muet","Chantonneur","Harmonieux","DJ","ROI DE LA FÊTE"],
    levelsF:["Muette","Chantonnante","Harmonieuse","DJ","REINE DE LA FÊTE"],
    taskVerb:"chantée", winMsg:"Branch approuve. Poppy aussi. Tout le monde chante. Tu ne peux pas fuir.",
    coinName:"Étincelle",
    platformBg:"#070009", platformColor:"#CC44AA", platformItem:"🎵",
    platformItems:["🎵","🎉","💃","🌺","🌟"], platformHazard:"🎹", platformObstacle:"☁️",
    charBodyColor:"#881177",
    shopCategory:{ id:"trolls", label:"🧌 Trolls", items:[
      {id:"tr1",emoji:"🌺",name:"Fleur dans les cheveux",cost:15,slot:"hat"},
      {id:"tr2",emoji:"✨",name:"Glitter tube",cost:20,slot:"themed"},
      {id:"tr3",emoji:"🤗",name:"Hug Time badge",cost:25,slot:"themed"},
      {id:"tr4",emoji:"🎤",name:"Micro de scène",cost:30,slot:"themed"},
      {id:"tr5",emoji:"🎶",name:"Notes musicales",cost:35,slot:"themed"},
      {id:"tr6",emoji:"💃",name:"Pas de danse légendaire",cost:50,slot:"themed"},
    ]},
  },
  // ── GHIBLI ────────────────────────────────────────────────
  ghibli: {
    id:"ghibli", name:"Univers Ghibli", icon:"🍃",
    bg:"#050d0a", primary:"#3A8A4A", accent:"#A8E6B0", glow:"#A8E6B0",
    levels:["Esprit de la Forêt","Voyageur","Héros Calme","Sage","TOTORO"],
    levelsF:["Esprit de la Forêt","Voyageuse","Héroïne Calme","Sage","TOTORO"],
    taskVerb:"contemplée", winMsg:"Chihiro a nettoyé des bains publics. Toi tu fais juste ta chambre.",
    coinName:"Esprit",
    platformBg:"#020806", platformColor:"#3A8A4A", platformItem:"🍃",
    platformItems:["🍃","🌸","🏮","🌳","✨"], platformHazard:"💨", platformObstacle:"🌳",
    charBodyColor:"#224433",
    shopCategory:{ id:"ghibli", label:"🍃 Ghibli", items:[
      {id:"gh1",emoji:"🚌",name:"Ticket Chat-Bus",cost:30,slot:"themed"},
      {id:"gh2",emoji:"🍃",name:"Feuille magique",cost:20,slot:"themed"},
      {id:"gh3",emoji:"🍱",name:"Bento du Studio",cost:25,slot:"themed"},
      {id:"gh4",emoji:"🦔",name:"Totoro de poche",cost:50,slot:"pet"},
      {id:"gh5",emoji:"🏮",name:"Lanterne du voyage",cost:35,slot:"themed"},
      {id:"gh6",emoji:"🎋",name:"Chapeau de paille",cost:15,slot:"hat"},
    ]},
  },
  // ── PLANÈTE DES SINGES ────────────────────────────────────
  singes: {
    id:"singes", name:"Planète des Singes", icon:"🐒",
    bg:"#0d0a00", primary:"#886600", accent:"#FFCC44", glow:"#FFCC44",
    levels:["Singe Paresseux","Grimpeur","Guerrier","Général","CÉSAR"],
    levelsF:["Singe Paresseuse","Grimpeuse","Guerrière","Générale","CÉSAR"],
    taskVerb:"conquise", winMsg:"César n'a jamais laissé traîner ses affaires. C'est pour ça qu'il a pris le pouvoir.",
    coinName:"Banane",
    platformBg:"#080600", platformColor:"#886600", platformItem:"🍌",
    platformItems:["🍌","🌴","⚔️","🏔️","👑"], platformHazard:"💥", platformObstacle:"🌴",
    charBodyColor:"#553300",
    shopCategory:{ id:"singes", label:"🐒 Singes", items:[
      {id:"si1",emoji:"⚔️",name:"Lance tribale",cost:25,slot:"themed"},
      {id:"si2",emoji:"🎖️",name:"Épaulettes de général",cost:35,slot:"themed"},
      {id:"si3",emoji:"🏅",name:"Médaille de la révolution",cost:40,slot:"themed"},
      {id:"si4",emoji:"🌴",name:"Couronne de palmes",cost:20,slot:"hat"},
      {id:"si5",emoji:"🍌",name:"Banane légendaire",cost:15,slot:"themed"},
      {id:"si6",emoji:"🦍",name:"Familier gorille",cost:60,slot:"pet"},
    ]},
  },
  // ── JAMES BOND ────────────────────────────────────────────
  jamesbond: {
    id:"jamesbond", name:"James Bond", icon:"🕵️",
    bg:"#050508", primary:"#223355", accent:"#C0A060", glow:"#C0A060",
    levels:["Stagiaire MI6","Agent","00X","007","M (le vrai boss)"],
    levelsF:["Stagiaire MI6","Agente","00X","007","M (la vraie boss)"],
    taskVerb:"infiltrée", winMsg:"Mission accomplie. Q est... modérément impressionné.",
    coinName:"Gadget",
    platformBg:"#020204", platformColor:"#223355", platformItem:"🔫",
    platformItems:["🔫","🎰","🍸","💼","🚗"], platformHazard:"💣", platformObstacle:"🏢",
    charBodyColor:"#111133",
    shopCategory:{ id:"jamesbond", label:"🕵️ MI6", items:[
      {id:"jb1",emoji:"🚗",name:"Aston Martin miniature",cost:50,slot:"themed"},
      {id:"jb2",emoji:"⌚",name:"Montre gadget",cost:40,slot:"themed"},
      {id:"jb3",emoji:"🤵",name:"Smoking légendaire",cost:35,slot:"themed"},
      {id:"jb4",emoji:"🍸",name:"Martini (au jus)",cost:15,slot:"themed"},
      {id:"jb5",emoji:"💼",name:"Mallette secrète",cost:30,slot:"themed"},
      {id:"jb6",emoji:"🕶️",name:"Lunettes espion",cost:20,slot:"hat"},
    ]},
  },
  // ── BOOMERANG FU ──────────────────────────────────────────
  boomerangfu: {
    id:"boomerangfu", name:"Boomerang Fu", icon:"💥",
    bg:"#0a0800", primary:"#CC6600", accent:"#FF9900", glow:"#FF9900",
    levels:["Pain Grillé","Croissant","Taco Ninja","Burger Boss","SEIGNEUR DU BOOMERANG"],
    levelsF:["Pain Grillé","Croissant","Taco Ninja","Burger Boss","SEIGNEUR DU BOOMERANG"],
    taskVerb:"lancée-revenue", winMsg:"Tu as lancé ton boomerang de tâche et il est revenu complété. Physique quantique.",
    coinName:"Boomerang",
    platformBg:"#070500", platformColor:"#CC6600", platformItem:"💥",
    platformItems:["💥","🥐","🌮","🍔","🏆"], platformHazard:"💥", platformObstacle:"🧱",
    charBodyColor:"#884400",
    shopCategory:{ id:"boomerangfu", label:"💥 Boomerang", items:[
      {id:"bf1",emoji:"🪃",name:"Boomerang doré",cost:35,slot:"themed"},
      {id:"bf2",emoji:"🥖",name:"Armure de baguette",cost:25,slot:"themed"},
      {id:"bf3",emoji:"🍕",name:"Chapeau chef ninja",cost:20,slot:"hat"},
      {id:"bf4",emoji:"💥",name:"Explosion de puissance",cost:40,slot:"themed"},
      {id:"bf5",emoji:"🌮",name:"Taco de victoire",cost:15,slot:"themed"},
      {id:"bf6",emoji:"🏆",name:"Trophée du pain",cost:50,slot:"themed"},
    ]},
  },
  // ── MINECRAFT ++ ──────────────────────────────────────────
  minecraftpp: {
    id:"minecraftpp", name:"Minecraft ++", icon:"⛏️",
    bg:"#0d1a0d", primary:"#4A9E34", accent:"#85CDD1", glow:"#85CDD1",
    levels:["Bois","Pierre","Fer","Or","DIAMANT LÉGENDAIRE"],
    levelsF:["Bois","Pierre","Fer","Or","DIAMANT LÉGENDAIRE"],
    taskVerb:"craftée", winMsg:"Steve a construit une maison entière en une nuit. Toi t'as rangé une brassée. Respect quand même.",
    coinName:"Diamant",
    platformBg:"#060e06", platformColor:"#4A9E34", platformItem:"💎",
    platformItems:["💎","⛏️","🪵","🔥","🏹"], platformHazard:"💀", platformObstacle:"🪨",
    charBodyColor:"#2A6E24",
    shopCategory:{ id:"minecraftpp", label:"⛏️ Minecraft", items:[
      {id:"mc1",emoji:"⛏️",name:"Pickaxe diamant",cost:35,slot:"themed"},
      {id:"mc2",emoji:"🗡️",name:"Épée enchantée",cost:40,slot:"themed"},
      {id:"mc3",emoji:"🛡️",name:"Totem d'immortalité",cost:60,slot:"themed"},
      {id:"mc4",emoji:"🪶",name:"Elytra",cost:50,slot:"themed"},
      {id:"mc5",emoji:"💎",name:"Bloc de diamant",cost:25,slot:"themed"},
      {id:"mc6",emoji:"🪖",name:"Casque Netherite",cost:30,slot:"hat"},
    ]},
  },
  // ── COURSE FUTURISTE ──────────────────────────────────────
  coursefutur: {
    id:"coursefutur", name:"Course Futuriste", icon:"🏎️",
    bg:"#000a14", primary:"#0055AA", accent:"#00AAFF", glow:"#00DDFF",
    levels:["Mécanicien","Pilote","Ace","Champion","PILOTE FANTÔME"],
    levelsF:["Mécanicien","Pilote","Ace","Champion","PILOTE FANTÔME"],
    taskVerb:"pilotée", winMsg:"Tu as complété ça à 300km/h. Mentalement, du moins.",
    coinName:"Boost",
    platformBg:"#000508", platformColor:"#0055AA", platformItem:"🏎️",
    platformItems:["🏎️","⚡","🏁","💨","🏆"], platformHazard:"💥", platformObstacle:"🚧",
    charBodyColor:"#002255",
    shopCategory:{ id:"coursefutur", label:"🏎️ Course", items:[
      {id:"cf1",emoji:"🪖",name:"Casque holographique",cost:30,slot:"hat"},
      {id:"cf2",emoji:"🚗",name:"Voiture miniature",cost:40,slot:"themed"},
      {id:"cf3",emoji:"⚡",name:"Turbo légendaire",cost:35,slot:"themed"},
      {id:"cf4",emoji:"🏁",name:"Drapeau du champion",cost:25,slot:"themed"},
      {id:"cf5",emoji:"🛞",name:"Aileron aérodynamique",cost:20,slot:"themed"},
      {id:"cf6",emoji:"💫",name:"Moteur fantôme",cost:50,slot:"themed"},
    ]},
  },
  // ── SECRET THEMES (random pool only) ─────────────────────
  canards: {
    id:"canards", name:"🦆 Canards Jaunes", icon:"🦆",
    bg:"#0a0d00", primary:"#DDAA00", accent:"#FFEE44", glow:"#FFEE44",
    levels:["Poussin","Caneton","Canard","Canard Pro","SUPER CANARD"],
    levelsF:["Poussin","Caneton","Canard","Canard Pro","SUPER CANARD"],
    taskVerb:"canardée", winMsg:"Coin coin! Tâche accomplie. Tu mérites un biscuit en forme de canard.",
    coinName:"Plume",
    platformBg:"#060800", platformColor:"#DDAA00", platformItem:"🦆",
    platformItems:["🦆","🪶","💛","🌊","⭐"], platformHazard:"🐊", platformObstacle:"🌾",
    charBodyColor:"#DDAA00", secret:true,
    shopCategory:{ id:"canards", label:"🦆 Canards", items:[
      {id:"dk1",emoji:"🦆",name:"Canard légendaire",cost:30,slot:"pet"},
      {id:"dk2",emoji:"🪶",name:"Plume d'or",cost:20,slot:"themed"},
      {id:"dk3",emoji:"💛",name:"Couronne jaune",cost:35,slot:"hat"},
      {id:"dk4",emoji:"🌊",name:"Mare privée",cost:40,slot:"themed"},
      {id:"dk5",emoji:"🐥",name:"Poussin familier",cost:15,slot:"pet"},
      {id:"dk6",emoji:"🛁",name:"Bain de canards",cost:25,slot:"themed"},
    ]},
  },
  aliens: {
    id:"aliens", name:"👽 Invasion Alien", icon:"👽",
    bg:"#000d00", primary:"#00AA44", accent:"#44FF88", glow:"#44FF88",
    levels:["Terrien","Contact","Abducté","Hybride","MAÎTRE GALACTIQUE"],
    levelsF:["Terrienne","Contact","Abductée","Hybride","MAÎTRE GALACTIQUE"],
    taskVerb:"abductée", winMsg:"Les Hommes en Noir approuvent. Probablement.",
    coinName:"Cristal",
    platformBg:"#000800", platformColor:"#00AA44", platformItem:"🛸",
    platformItems:["🛸","💚","🔭","⭐","👾"], platformHazard:"🔦", platformObstacle:"🪨",
    charBodyColor:"#003322", secret:true,
    shopCategory:{ id:"aliens", label:"👽 Alien", items:[
      {id:"al1",emoji:"🛸",name:"Soucoupe volante",cost:40,slot:"pet"},
      {id:"al2",emoji:"👽",name:"Masque alien",cost:30,slot:"hat"},
      {id:"al3",emoji:"💚",name:"Cristal vert",cost:20,slot:"themed"},
      {id:"al4",emoji:"🌌",name:"Carte galactique",cost:35,slot:"themed"},
      {id:"al5",emoji:"👾",name:"Familier pixel",cost:15,slot:"pet"},
      {id:"al6",emoji:"🔬",name:"Rayon analyseur",cost:25,slot:"themed"},
    ]},
  },
  pirates: {
    id:"pirates", name:"🏴 Pirates", icon:"🏴",
    bg:"#080500", primary:"#885500", accent:"#FFAA22", glow:"#FFAA22",
    levels:["Mousse","Matelot","Pirate","Capitaine","PIRATE LÉGENDAIRE"],
    levelsF:["Mousse","Matelote","Pirate","Capitaine","PIRATE LÉGENDAIRE"],
    taskVerb:"pillée", winMsg:"Yo ho ho! Le trésor est à toi. Range quand même ta chambre.",
    coinName:"Doubloon",
    platformBg:"#040300", platformColor:"#885500", platformItem:"🪝",
    platformItems:["🪝","💰","🗺️","🦜","💎"], platformHazard:"🦈", platformObstacle:"🌊",
    charBodyColor:"#442200", secret:true,
    shopCategory:{ id:"pirates", label:"🏴 Pirates", items:[
      {id:"pi1",emoji:"🦜",name:"Perroquet pirate",cost:25,slot:"pet"},
      {id:"pi2",emoji:"🎩",name:"Chapeau de capitaine",cost:30,slot:"hat"},
      {id:"pi3",emoji:"⚔️",name:"Sabre du corsaire",cost:35,slot:"themed"},
      {id:"pi4",emoji:"💰",name:"Coffre au trésor",cost:50,slot:"themed"},
      {id:"pi5",emoji:"🗺️",name:"Carte au trésor",cost:20,slot:"themed"},
      {id:"pi6",emoji:"🔭",name:"Longue-vue",cost:15,slot:"themed"},
    ]},
  },
  sushi: {
    id:"sushi", name:"🍣 Sushi World", icon:"🍣",
    bg:"#0a0005", primary:"#CC0033", accent:"#FF6688", glow:"#FF6688",
    levels:["Riz nature","Maki","California","Nigiri","CHEF SUSHI ULTIME"],
    levelsF:["Riz nature","Maki","California","Nigiri","CHEF SUSHI ULTIME"],
    taskVerb:"roulée", winMsg:"Itadakimasu! Tâche accomplie avec grâce et wasabi.",
    coinName:"Maki",
    platformBg:"#050003", platformColor:"#CC0033", platformItem:"🍣",
    platformItems:["🍣","🥢","🍱","🐟","⭐"], platformHazard:"🦑", platformObstacle:"🌊",
    charBodyColor:"#660011", secret:true,
    shopCategory:{ id:"sushi", label:"🍣 Sushi", items:[
      {id:"su1",emoji:"🍣",name:"Sushi légendaire",cost:25,slot:"themed"},
      {id:"su2",emoji:"🥢",name:"Baguettes en or",cost:20,slot:"themed"},
      {id:"su3",emoji:"🍱",name:"Bento de champion",cost:30,slot:"themed"},
      {id:"su4",emoji:"🎌",name:"Bandeau chef",cost:35,slot:"hat"},
      {id:"su5",emoji:"🌊",name:"Vague de wasabi",cost:15,slot:"themed"},
      {id:"su6",emoji:"🐡",name:"Fugu familier",cost:40,slot:"pet"},
    ]},
  },
  robots: {
    id:"robots", name:"🤖 Robots", icon:"🤖",
    bg:"#000510", primary:"#0044AA", accent:"#00AAFF", glow:"#00CCFF",
    levels:["Grille-pain","Aspirateur","Robot","Cyborg","INTELLIGENCE ARTIFICIELLE"],
    levelsF:["Grille-pain","Aspirateur","Robot","Cyborg","INTELLIGENCE ARTIFICIELLE"],
    taskVerb:"calculée", winMsg:"TÂCHE_COMPLÉTÉE = TRUE. FÉLICITATIONS.EXE",
    coinName:"Pixel",
    platformBg:"#000308", platformColor:"#0044AA", platformItem:"🤖",
    platformItems:["🤖","⚙️","💾","🔩","⭐"], platformHazard:"🔌", platformObstacle:"🖥️",
    charBodyColor:"#002255", secret:true,
    shopCategory:{ id:"robots", label:"🤖 Robots", items:[
      {id:"ro1",emoji:"🤖",name:"Tête de robot",cost:30,slot:"hat"},
      {id:"ro2",emoji:"🦾",name:"Bras robotique",cost:35,slot:"themed"},
      {id:"ro3",emoji:"💾",name:"Disque dur rare",cost:25,slot:"themed"},
      {id:"ro4",emoji:"⚡",name:"Batterie infinie",cost:40,slot:"themed"},
      {id:"ro5",emoji:"📡",name:"Antenne satellite",cost:20,slot:"hat"},
      {id:"ro6",emoji:"🖥️",name:"Écran intégré",cost:50,slot:"themed"},
    ]},
  },
  // ── JAPON ────────────────────────────────────────────────────
  japon: {
    id:"japon", name:"Japon", icon:"⛩️",
    bg:"#08000a", primary:"#CC0044", accent:"#FF4488", glow:"#FF4488",
    levels:["Shōshin","Genin","Chūnin","Jōnin","SHOGUN"],
    levelsF:["Shōshin","Genin","Chūnin","Jōnin","SHOGUN"],
    taskVerb:"maîtrisée", winMsg:"Ichi-go ichi-e. Ce moment ne reviendra pas. T'as bien fait.",
    coinName:"Mon",
    platformBg:"#040005", platformColor:"#CC0044", platformItem:"⛩️",
    platformItems:["⛩️","🌸","🎋","🏯","⚔️"], platformHazard:"🔥", platformObstacle:"🪨",
    charBodyColor:"#440022",
    xpUnlock:200,
    shopCategory:{ id:"japon", label:"⛩️ Japon", items:[
      {id:"jp1",emoji:"⛩️",name:"Torii personnel",cost:40,slot:"themed"},
      {id:"jp2",emoji:"🌸",name:"Fleur de cerisier",cost:20,slot:"themed"},
      {id:"jp3",emoji:"⚔️",name:"Katana légendaire",cost:50,slot:"themed"},
      {id:"jp4",emoji:"🥷",name:"Armure de ninja",cost:35,slot:"themed"},
      {id:"jp5",emoji:"🎋",name:"Brin de bambou",cost:15,slot:"themed"},
      {id:"jp6",emoji:"🗡️",name:"Casque samurai",cost:30,slot:"hat"},
    ]},
  },
  // ── LICORNES ET PAILLETTES ────────────────────────────────────
  licornes: {
    id:"licornes", name:"Licornes ✨", icon:"🦄",
    bg:"#0f000f", primary:"#DD44FF", accent:"#FFAAFF", glow:"#FFAAFF",
    levels:["Poussiéreux","Scintillant","Brillant","Étincelant","DÉESSE DU GLITTER"],
    levelsF:["Poussiéreuse","Scintillante","Brillante","Étincelante","DÉESSE DU GLITTER"],
    taskVerb:"pailletée", winMsg:"Félicitations! Tu peux maintenant lancer des paillettes partout. Bonne chance pour le nettoyage.",
    coinName:"Paillette",
    platformBg:"#09000f", platformColor:"#DD44FF", platformItem:"🦄",
    platformItems:["🦄","🌈","✨","💎","🌸"], platformHazard:"💥", platformObstacle:"☁️",
    charBodyColor:"#8800AA",
    xpUnlock:100,
    shopCategory:{ id:"licornes", label:"🦄 Licornes", items:[
      {id:"lc1",emoji:"🦄",name:"Corne de licorne",cost:50,slot:"hat"},
      {id:"lc2",emoji:"🌈",name:"Queue arc-en-ciel",cost:35,slot:"themed"},
      {id:"lc3",emoji:"✨",name:"Manteau de paillettes",cost:40,slot:"themed"},
      {id:"lc4",emoji:"💎",name:"Diamant magique",cost:45,slot:"themed"},
      {id:"lc5",emoji:"🧁",name:"Cupcake licorne",cost:20,slot:"themed"},
      {id:"lc6",emoji:"🌸",name:"Couronne fleurie",cost:25,slot:"hat"},
    ]},
  },
  // ── MARVEL ───────────────────────────────────────────────────
  marvel: {
    id:"marvel", name:"Marvel", icon:"⚡",
    bg:"#05000f", primary:"#CC1111", accent:"#D97070", glow:"#FF8888",
    levels:["Civil","Agent S.H.I.E.L.D","Avenger","Super-héros","VENGEUR LÉGENDAIRE"],
    levelsF:["Civile","Agente S.H.I.E.L.D","Avenger","Super-héroïne","VENGERESSE LÉGENDAIRE"],
    taskVerb:"sauvée", winMsg:"L'univers est en sécurité. Pour l'instant. Va ranger ta chambre, Spider-Man.",
    coinName:"Vibranium",
    platformBg:"#030008", platformColor:"#CC1111", platformItem:"⚡",
    platformItems:["⚡","🛡️","🕷️","⭐","💎"], platformHazard:"💥", platformObstacle:"🏢",
    charBodyColor:"#660000",
    xpUnlock:300,
    shopCategory:{ id:"marvel", label:"⚡ Marvel", items:[
      {id:"mv1",emoji:"🛡️",name:"Bouclier de Captain America",cost:60,slot:"themed"},
      {id:"mv2",emoji:"🕷️",name:"Toile de Spider-Man",cost:35,slot:"themed"},
      {id:"mv3",emoji:"⚡",name:"Marteau de Thor",cost:50,slot:"themed"},
      {id:"mv4",emoji:"🪖",name:"Casque d'Iron Man",cost:40,slot:"hat"},
      {id:"mv5",emoji:"💎",name:"Pierre de l'Infini",cost:55,slot:"themed"},
      {id:"mv6",emoji:"🦾",name:"Bras Vibranium",cost:45,slot:"themed"},
    ]},
  },
  // ── DISNEY ───────────────────────────────────────────────────
  disney: {
    id:"disney", name:"Disney", icon:"🏰",
    bg:"#000810", primary:"#0044CC", accent:"#66AAFF", glow:"#88CCFF",
    levels:["Spectateur","Apprenti Magicien","Héros","Prince/Princesse","MAÎTRE MAGICIEN"],
    levelsF:["Spectatrice","Apprentie Magicienne","Héroïne","Princesse","MAÎTRE MAGICIENNE"],
    taskVerb:"enchantée", winMsg:"Bibbidi-Bobbidi-Boo! La tâche est faite. Cendrillon rangeait sans plaindre, juste dit.",
    coinName:"Étoile de souhait",
    platformBg:"#000508", platformColor:"#0044CC", platformItem:"🏰",
    platformItems:["🏰","⭐","🧚","🎠","🌟"], platformHazard:"🧙", platformObstacle:"☁️",
    charBodyColor:"#002266",
    xpUnlock:250,
    shopCategory:{ id:"disney", label:"🏰 Disney", items:[
      {id:"di1",emoji:"🏰",name:"Château miniature",cost:45,slot:"themed"},
      {id:"di2",emoji:"🧚",name:"Fée Clochette",cost:35,slot:"pet"},
      {id:"di3",emoji:"⭐",name:"Étoile de souhait",cost:30,slot:"themed"},
      {id:"di4",emoji:"🎪",name:"Chapeau de Mickey",cost:25,slot:"hat"},
      {id:"di5",emoji:"🎠",name:"Carrousel enchanté",cost:50,slot:"themed"},
      {id:"di6",emoji:"🌹",name:"Rose de la Bête",cost:40,slot:"themed"},
    ]},
  },
  // ── PIXAR ────────────────────────────────────────────────────
  pixar: {
    id:"pixar", name:"Pixar", icon:"💡",
    bg:"#00060f", primary:"#0066CC", accent:"#44AAFF", glow:"#66CCFF",
    levels:["Idée","Étincelle","Aventurier","Héros Animé","PIXAR STAR"],
    levelsF:["Idée","Étincelle","Aventurière","Héroïne Animée","PIXAR STAR"],
    taskVerb:"animée", winMsg:"WALL-E nettoyait la Terre entière. Toi t'as fait ta chambre. On est loin, mais c'est un début.",
    coinName:"Étoile Pixar",
    platformBg:"#000408", platformColor:"#0066CC", platformItem:"💡",
    platformItems:["💡","🤖","🐟","🚀","⭐"], platformHazard:"💥", platformObstacle:"🌊",
    charBodyColor:"#003366",
    xpUnlock:350,
    shopCategory:{ id:"pixar", label:"💡 Pixar", items:[
      {id:"px1",emoji:"🤖",name:"WALL-E miniature",cost:50,slot:"pet"},
      {id:"px2",emoji:"🐟",name:"Nemo en bocal",cost:35,slot:"pet"},
      {id:"px3",emoji:"🚀",name:"Vaisseau Buzz",cost:45,slot:"themed"},
      {id:"px4",emoji:"💡",name:"Lampe Luxo",cost:30,slot:"themed"},
      {id:"px5",emoji:"🎈",name:"Bouquet de ballons",cost:25,slot:"themed"},
      {id:"px6",emoji:"🪖",name:"Casque de pompier",cost:20,slot:"hat"},
    ]},
  },

};
// XP thresholds for theme unlock (applied at load time to avoid editing every entry)
export const THEME_XP_UNLOCK = {
  none:0, lego:0, medieval:50, kpop:50,
  unicorn:100, demon:100, licornes:100,
  angel:150, scientifique:150, roblox:150,
  harrypotter:200, ghibli:200, insectes:200, japon:200,
  monstres:250, prehistoire:250, horreur:250, disney:250,
  boomerangfu:300, microscopique:300, bisounours:300, marvel:300,
  singes:350, geantdefer:350, trolls:350, jamesbond:350, cuisine:350,
  minecraftpp:400, coursefutur:400, melange:400, pixar:350,
  // secret — unlocked only via random (secret flag bypasses XP)
  canards:999, aliens:999, pirates:999, sushi:999, robots:999,
};
Object.keys(PLAYER_THEMES).forEach(k => {
  if (PLAYER_THEMES[k].xpUnlock === undefined)
    PLAYER_THEMES[k].xpUnlock = THEME_XP_UNLOCK[k] ?? 0;
});

export const PT_LIST = Object.values(PLAYER_THEMES);
export const getPlayerTheme = (id) => PLAYER_THEMES[id] || PLAYER_THEMES.none;

// ─── CATALOGUE BOUTIQUE (niveau module pour que le PROFIL puisse résoudre les items) ──
export const BASE_SHOP_ITEMS = {
  hats:[{id:"h1",emoji:"🎩",name:"Chapeau magique",cost:20,slot:"hat"},{id:"h2",emoji:"👑",name:"Couronne",cost:40,slot:"hat"},{id:"h3",emoji:"⛑",name:"Casque héros",cost:25,slot:"hat"},{id:"h4",emoji:"🪖",name:"Casque diamant",cost:35,slot:"hat"},{id:"h5",emoji:"🎓",name:"Chapeau savant",cost:30,slot:"hat"},{id:"h6",emoji:"🧢",name:"Cap champion",cost:15,slot:"hat"}],
  armors:[{id:"a1",emoji:"🛡️",name:"Bouclier",cost:15,slot:"armor"},{id:"a2",emoji:"⚔️",name:"Épée",cost:20,slot:"armor"},{id:"a3",emoji:"🏹",name:"Arc en or",cost:35,slot:"armor"},{id:"a4",emoji:"💎",name:"Armure diamant",cost:50,slot:"armor"},{id:"a5",emoji:"🪄",name:"Bâton magique",cost:30,slot:"armor"}],
  pets:[{id:"p1",emoji:"🐱",name:"Chat",cost:20,slot:"pet"},{id:"p2",emoji:"🐶",name:"Chien",cost:20,slot:"pet"},{id:"p3",emoji:"🐺",name:"Loup",cost:35,slot:"pet"},{id:"p4",emoji:"🦊",name:"Renard",cost:30,slot:"pet"},{id:"p5",emoji:"🐉",name:"Dragon",cost:60,slot:"pet"},{id:"p6",emoji:"🦜",name:"Perroquet",cost:25,slot:"pet"},{id:"pet_duck",emoji:"🦆",name:"Canard jaune",cost:20,slot:"pet"},{id:"pet_worm",emoji:"🪱",name:"Ver de terre",cost:15,slot:"pet"},{id:"pet_capy",emoji:"🦫",name:"Capybara",cost:40,slot:"pet"},{id:"pet_bee",emoji:"🐝",name:"Abeille",cost:25,slot:"pet"},{id:"pet_spider",emoji:"🕷️",name:"Araignée",cost:30,slot:"pet"}],
};
export const ALL_SHOP_ITEMS = [
  ...BASE_SHOP_ITEMS.hats, ...BASE_SHOP_ITEMS.armors, ...BASE_SHOP_ITEMS.pets,
  ...PT_LIST.flatMap(t => t.shopCategory?.items || []),
];
export const shopItemById = (id) => ALL_SHOP_ITEMS.find(i => i.id === id);
// v1.74.0 — pool d'items ULTRA LÉGENDAIRES (rareté Légendaire/Unique, coût ≥45) pour la récompense de victoire de boss
export const ULTRA_ITEMS = ALL_SHOP_ITEMS.filter(i => (i.cost||0) >= 45);
export const pickUltraLegendary = () => ULTRA_ITEMS[Math.floor(Math.random()*ULTRA_ITEMS.length)] || ALL_SHOP_ITEMS[0];
